# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"symbol_map": "00_core.ipynb",
         "get_ohlcv_from_db": "00_core.ipynb",
         "from_db_load_df_for": "00_core.ipynb",
         "load_binance_data": "00_core.ipynb",
         "load_both_datasources": "00_core.ipynb",
         "compare_timeseries": "00_core.ipynb",
         "previous_local_data_exists": "00_core.ipynb",
         "load_data_keep_best": "00_core.ipynb",
         "add_BTC_price_as_column": "00_core.ipynb",
         "build_segmented_parts": "00_core.ipynb",
         "check_for_RSI_buys": "00_core.ipynb",
         "add_indicator": "01_indicators.ipynb"}

modules = ["core.py",
           "indicators.py"]

doc_url = "https://pnmartinez.github.io/simpler_backtest/"

git_url = "https://github.com/pnmartinez/simpler_backtest/tree/master/"

def custom_doc_links(name): return None
