# AUTOGENERATED! DO NOT EDIT! File to edit: 01_indicators.ipynb (unless otherwise specified).

__all__ = ['add_indicator']

# Cell
import talib

# Cell
def add_indicator(indicator_name, df):
    """
    Calls TA-Lib functions parsing their
    namestring to a proper function call,
    and attaches as new column on df
    """
    # Notebook was designed for RSI
    indicator = indicator_name + '_indicator'
    df[indicator] = getattr(talib, indicator_name)(df.close)

    # We drop all zeros on RSI that come from no volume traded
#     non_zeros = df[(df[indicator] != 0)]
#     non_zeros.head
#     df = non_zeros

#     # drop NaNs
#     df = df.dropna()

    return df