# -*- coding: utf-8 -*-
"""Genomic sequences."""
SECONDS_BETWEEN_UCSC_REQUESTS = 10
# for displaying vertical alignments
VERTICAL_ALIGNMENT_MATCH_CHARACTER = "|"
VERTICAL_ALIGNMENT_MISMATCH_CHARACTER = "X"
ALIGNMENT_GAP_CHARACTER = "-"
VERTICAL_ALIGNMENT_GAP_CHARACTER = " "
