
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-10-07T10:24:31-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "cbd3ffe602f5f70df7b20a922845569b0d9ad98a",
 "version": "2020.10.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
