
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-10-03T21:17:22+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "04bb98c9da58fd73157e4fa1e6177cdadb233ba6",
 "version": "v0.2.9-rc01"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
