
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-10-09T11:53:44-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "1a25aa07f5d19ef1747375083a5435383a66fc52",
 "version": "v0.7.14"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
