
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-10-05T19:16:20+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "250782273a1a06791b8e00f4b713d91f8b99c29e",
 "version": "1.0.15"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
