#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['sartoriusb']

package_data = \
{'': ['*']}

install_requires = \
['pyserial >= 3.4']

extras_require = \
{'dev': ['black',
         'flake8',
         'flake8-comprehensions',
         'isort',
         'keyring',
         'pre-commit'],
 'test': ['pytest >=4.0.0', 'pytest-cov', 'pytest-mock']}

setup(name='SartoriUSB',
      version='0.2.5',
      description='pysartoriusb',
      author='Holger Frey',
      author_email='frey@imtek.de',
      url='https://github.com/holgi/sartoriusb',
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      extras_require=extras_require,
      python_requires='>=3.7',
     )
