
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-10-07T22:52:13+0900",
 "dirty": false,
 "error": null,
 "full-revisionid": "2f9746f4b5003798086f87ca44fe22d018e96234",
 "version": "0.3.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
