
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-10-05T18:57:21-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "53ce4923e334085d71c2d39335f1fc1a0c3c4a48",
 "version": "2020.10.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
