
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-10-05T21:21:14-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "06680567fdd67d5fb9ca552489ad4def7fc429b8",
 "version": "0.0.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
