
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-09-30T21:11:09+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "ddefda1cf6163ccb2301a64495397c43696dbf82",
 "version": "2.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
