
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-10-06T13:50:54-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "14982bd900f17a66acc3930ec1a2ff138716d198",
 "version": "0.50a1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
