
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-10-02T00:00:30+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "c9034d8358bff2ad4a4c261dcf610f84faeb8bec",
 "version": "v0.6.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
