
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-09-30T20:28:51+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "eae710e5de45333ef4ab5b36c2642a310e156b45",
 "version": "0.1.18"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
