
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-10-05T17:40:19-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "f7b15bd0f134661c00976ee6fe9390c5e47df442",
 "version": "2020.10.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
