
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-10-03T16:16:18-0600",
 "dirty": true,
 "error": null,
 "full-revisionid": "fd5c451b8120f4c6728cddd2436707d382d8131f",
 "version": "0.3.1.post.dev1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
