
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "c025bd20053717ef2a1198974f324e1aeb71d020",
 "version": "2.6.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
