
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-10-02T13:08:55+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "d1341f83b8de0d8726491372d4a634c10eb807cd",
 "version": "v1.0.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
