
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-09-30T11:38:41-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "36743a532cd5ab9717a2ce8635f01e9b8d08c0af",
 "version": "v0.7.12"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
