# Generated by Django 2.2.4 on 2020-02-25 15:46

import django.core.validators
from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.StructBlock([('header_level', wagtail.core.blocks.ChoiceBlock(choices=[('h1', 'H1'), ('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4'), ('h5', 'H5'), ('h6', 'H6')], label='Header level')), ('text', wagtail.core.blocks.CharBlock(label='Text'))])), ('link', wagtail.core.blocks.StructBlock([('description', wagtail.core.blocks.CharBlock(label='Description')), ('url', wagtail.core.blocks.URLBlock(label='URL', validators=[django.core.validators.URLValidator(['http', 'https', 'ftp', 'ftps', 'mailto', 'xmpp', 'tel'])]))])), ('person', wagtail.core.blocks.StructBlock([('person_page', wagtail.core.blocks.PageChooserBlock(label='Person or author page', page_type=['wagtailperson.PersonPage']))])), ('paragraph', wagtail.core.blocks.RichTextBlock())], blank=True),
        ),
    ]
