# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tensorflow_quantum/core/proto/pauli_sum.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tensorflow_quantum/core/proto/pauli_sum.proto',
  package='tfq.proto',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n-tensorflow_quantum/core/proto/pauli_sum.proto\x12\ttfq.proto\"/\n\x08PauliSum\x12#\n\x05terms\x18\x01 \x03(\x0b\x32\x14.tfq.proto.PauliTerm\"j\n\tPauliTerm\x12\x18\n\x10\x63oefficient_real\x18\x01 \x01(\x02\x12\x18\n\x10\x63oefficient_imag\x18\x02 \x01(\x02\x12)\n\x06paulis\x18\x03 \x03(\x0b\x32\x19.tfq.proto.PauliQubitPair\"6\n\x0ePauliQubitPair\x12\x10\n\x08qubit_id\x18\x01 \x01(\t\x12\x12\n\npauli_type\x18\x02 \x01(\tb\x06proto3')
)




_PAULISUM = _descriptor.Descriptor(
  name='PauliSum',
  full_name='tfq.proto.PauliSum',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='terms', full_name='tfq.proto.PauliSum.terms', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=60,
  serialized_end=107,
)


_PAULITERM = _descriptor.Descriptor(
  name='PauliTerm',
  full_name='tfq.proto.PauliTerm',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='coefficient_real', full_name='tfq.proto.PauliTerm.coefficient_real', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='coefficient_imag', full_name='tfq.proto.PauliTerm.coefficient_imag', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='paulis', full_name='tfq.proto.PauliTerm.paulis', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=109,
  serialized_end=215,
)


_PAULIQUBITPAIR = _descriptor.Descriptor(
  name='PauliQubitPair',
  full_name='tfq.proto.PauliQubitPair',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='qubit_id', full_name='tfq.proto.PauliQubitPair.qubit_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pauli_type', full_name='tfq.proto.PauliQubitPair.pauli_type', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=217,
  serialized_end=271,
)

_PAULISUM.fields_by_name['terms'].message_type = _PAULITERM
_PAULITERM.fields_by_name['paulis'].message_type = _PAULIQUBITPAIR
DESCRIPTOR.message_types_by_name['PauliSum'] = _PAULISUM
DESCRIPTOR.message_types_by_name['PauliTerm'] = _PAULITERM
DESCRIPTOR.message_types_by_name['PauliQubitPair'] = _PAULIQUBITPAIR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PauliSum = _reflection.GeneratedProtocolMessageType('PauliSum', (_message.Message,), {
  'DESCRIPTOR' : _PAULISUM,
  '__module__' : 'tensorflow_quantum.core.proto.pauli_sum_pb2'
  # @@protoc_insertion_point(class_scope:tfq.proto.PauliSum)
  })
_sym_db.RegisterMessage(PauliSum)

PauliTerm = _reflection.GeneratedProtocolMessageType('PauliTerm', (_message.Message,), {
  'DESCRIPTOR' : _PAULITERM,
  '__module__' : 'tensorflow_quantum.core.proto.pauli_sum_pb2'
  # @@protoc_insertion_point(class_scope:tfq.proto.PauliTerm)
  })
_sym_db.RegisterMessage(PauliTerm)

PauliQubitPair = _reflection.GeneratedProtocolMessageType('PauliQubitPair', (_message.Message,), {
  'DESCRIPTOR' : _PAULIQUBITPAIR,
  '__module__' : 'tensorflow_quantum.core.proto.pauli_sum_pb2'
  # @@protoc_insertion_point(class_scope:tfq.proto.PauliQubitPair)
  })
_sym_db.RegisterMessage(PauliQubitPair)


# @@protoc_insertion_point(module_scope)
