
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-10-01T22:16:06+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "ff407622afb08d5f100241731bd2a4a7f46bc3ac",
 "version": "v0.0.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
