
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-10-03T20:08:28-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "9ac8d0297663dd5dffc780739e564d26739e3ced",
 "version": "2020.10.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
