
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-09-25T12:47:23-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "b5a64d2204e31c21336cb6b96fcfee82949feb06",
 "version": "3.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
