
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "e3f2caadf79bcb53999698caf77125f2729e7714",
 "version": "0.4a1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
