#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['jirafrog']

package_data = \
{'': ['*']}

install_requires = \
['appdirs~=1.4.4', 'jira~=2.0.0', 'blessed~=1.17.10', 'toml~=0.10.0']

entry_points = \
{'console_scripts': ['jirafrog = jirafrog:main.main']}

setup(name='jirafrog',
      version='0.2.2',
      description='Extremely basic curses-based Jira UI',
      author='Andrew Magee',
      author_email='amagee@gmail.com',
      url='https://github.com/amagee/jirafrog',
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      entry_points=entry_points,
     )
