# coding: utf-8

"""
    Nomad Envoy

    This is the API descriptor for the Nomad Envoy API, responsible for order creation and product lists. Developed by `Samarkand Global <https://samarkand.global>`_ in partnership with `Youzan <https://www.youzan.com/>`_, `LittleRED <https://www.xiaohongshu.com/>`_, `PDD <http://www.pinduoduo.com/>`_, etc. Read the documentation online at `Nomad API Suite <https://api.samarkand.io/>`_ and Check out the detailed `changelog <https://gitlab.com/samarkand-nomad/nomad_readme/-/raw/master/history/nomad_envoy.md>`_. - Install for node with ``npm install nomad_envoy_cli`` - Install for python with ``pip install nomad-envoy-cli``  # noqa: E501

    The version of the OpenAPI document: 1.41.2
    Contact: paul@samarkand.global
    Generated by: https://openapi-generator.tech
"""


from setuptools import setup, find_packages  # noqa: H301

NAME = "nomad-envoy-cli"
VERSION = "1.41.2"
# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

REQUIRES = ["urllib3 >= 1.15", "six >= 1.10", "certifi", "python-dateutil"]

setup(
    name=NAME,
    version=VERSION,
    description="Nomad Envoy",
    author="OpenAPI Generator community",
    author_email="paul@samarkand.global",
    url="",
    keywords=["OpenAPI", "OpenAPI-Generator", "Nomad Envoy"],
    install_requires=REQUIRES + ["querystring==0.1.0"],
    packages=find_packages(exclude=["test", "tests"]),
    include_package_data=True,
    long_description="""\
    This is the API descriptor for the Nomad Envoy API, responsible for order creation and product lists. Developed by &#x60;Samarkand Global &lt;https://samarkand.global&gt;&#x60;_ in partnership with &#x60;Youzan &lt;https://www.youzan.com/&gt;&#x60;_, &#x60;LittleRED &lt;https://www.xiaohongshu.com/&gt;&#x60;_, &#x60;PDD &lt;http://www.pinduoduo.com/&gt;&#x60;_, etc. Read the documentation online at &#x60;Nomad API Suite &lt;https://api.samarkand.io/&gt;&#x60;_ and Check out the detailed &#x60;changelog &lt;https://gitlab.com/samarkand-nomad/nomad_readme/-/raw/master/history/nomad_envoy.md&gt;&#x60;_. - Install for node with &#x60;&#x60;npm install nomad_envoy_cli&#x60;&#x60; - Install for python with &#x60;&#x60;pip install nomad-envoy-cli&#x60;&#x60;  # noqa: E501
    """
)
