
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-10-08T16:03:32-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "1c364a4beec28891fda55d1c64bcd0e599f6d81f",
 "version": "2020.10.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
