
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-10-08T18:51:17-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "de0ef4370746fe236890cd9aadd491ec246eac20",
 "version": "0.3.5.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
