"""
This file is automatically generated during the setup.
Please do not edit config.py, but edit config.py.in in the root directory.
"""

LIME_PATH = "/tmp/pip-build-env-d05r2x_w/overlay/lib/python3.8/site-packages/lyncs_clime"
WITH_CLIME = "ON" == "ON"
