#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['pyramid_listing']

package_data = \
{'': ['*']}

install_requires = \
['SQLAlchemy']

extras_require = \
{'dev': ['black',
         'flake8',
         'flake8-comprehensions',
         'isort',
         'keyring',
         'pre-commit',
         'Sphinx'],
 'test': ['pytest >=4.0.0', 'pytest-cov', 'pytest-mock', 'tox']}

setup(name='pyramid_listing',
      version='0.2.2',
      description='Pyramid List Pagination contains helpers for pagination of result lists.',
      author='Holger Frey',
      author_email='mail@holgerfrey.de',
      url='https://github.com/holgi/pyramid_listing',
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      extras_require=extras_require,
      python_requires='>=3.7',
     )
