
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-09-30T15:59:23-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "e1c8a617dcbb0b22e5ff75dbd596539b2fcf587e",
 "version": "0.2.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
