
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-10-07T11:49:06+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "af3a3e09afb073b1250b539a42f8cd563ddc7a79",
 "version": "0.0.23"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
