
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-10-08T19:17:58-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "61f1732f2bd39c813997f030b1fd56aac77d4a4e",
 "version": "0.3.5.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
