
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-10-01T14:46:34+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "75b15e08fa59b559d67a56470f3b0ece5b05aade",
 "version": "0.0.51"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
