#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['qtypes', 'qtypes.widgets']

package_data = \
{'': ['*']}

install_requires = \
['toml', 'qtpy']

extras_require = \
{'dev': ['black', 'pre-commit']}

setup(name='qtypes',
      version='0.2.0',
      description='Build qt graphical user interfaces out of simple type objects.',
      author='Blaise Thompson',
      author_email='blaise@untzag.com',
      url='https://gitlab.com/yaq/qtypes',
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      extras_require=extras_require,
     )
