# Generated by Django 2.2.12 on 2020-05-13 15:20

from django.db import migrations
import djangocms_socialshare.models
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_socialshare', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialsharebutton',
            name='type',
            field=enumfields.fields.EnumField(default=None, enum=djangocms_socialshare.models.Type, max_length=32),
        ),
    ]
