# Generated by Django 2.2.13 on 2020-06-08 15:20

from django.db import migrations
import djangocms_socialshare.models
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_socialshare', '0003_add_social_links_plugin'),
    ]

    operations = [
        migrations.AddField(
            model_name='sociallinkspluginmodel',
            name='background_color',
            field=enumfields.fields.EnumField(default='dark', enum=djangocms_socialshare.models.BackgroundColor, max_length=32),
        ),
        migrations.AddField(
            model_name='socialsharepluginmodel',
            name='background_color',
            field=enumfields.fields.EnumField(default='dark', enum=djangocms_socialshare.models.BackgroundColor, max_length=32),
        ),
    ]
