
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-10-01T10:06:45-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "9171361855bfb3aede9334b4fadb5bb31e826e4c",
 "version": "v0.14.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
