
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

# pylint: disable=C0103

import json

version_json = '''
{
 "date": "2020-10-05T20:16:28+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "246403336bab13ee73f84e6059f5b7f8eef58f6f",
 "version": "1.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
