
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-10-03T06:15:40+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "6c9b67eb5c5a5ccbb47373e413730c63db7cea77",
 "version": "0.1.21"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
