# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: model_server/server.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from model_server.apis import predict_pb2 as model__server_dot_apis_dot_predict__pb2
from model_server.protos import model_info_pb2 as model__server_dot_protos_dot_model__info__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='model_server/server.proto',
  package='ModelServer',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x19model_server/server.proto\x12\x0bModelServer\x1a\x1fmodel_server/apis/predict.proto\x1a$model_server/protos/model_info.proto2\x9e\x01\n\x0bModelServer\x12M\n\x0eGetPredictions\x12\x1b.ModelServer.PredictRequest\x1a\x1c.ModelServer.PredictResponse\"\x00\x12@\n\x0cGetModelInfo\x12\x16.ModelServer.ModelInfo\x1a\x16.ModelServer.ModelInfo\"\x00\x62\x06proto3'
  ,
  dependencies=[model__server_dot_apis_dot_predict__pb2.DESCRIPTOR,model__server_dot_protos_dot_model__info__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_MODELSERVER = _descriptor.ServiceDescriptor(
  name='ModelServer',
  full_name='ModelServer.ModelServer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=114,
  serialized_end=272,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetPredictions',
    full_name='ModelServer.ModelServer.GetPredictions',
    index=0,
    containing_service=None,
    input_type=model__server_dot_apis_dot_predict__pb2._PREDICTREQUEST,
    output_type=model__server_dot_apis_dot_predict__pb2._PREDICTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetModelInfo',
    full_name='ModelServer.ModelServer.GetModelInfo',
    index=1,
    containing_service=None,
    input_type=model__server_dot_protos_dot_model__info__pb2._MODELINFO,
    output_type=model__server_dot_protos_dot_model__info__pb2._MODELINFO,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_MODELSERVER)

DESCRIPTOR.services_by_name['ModelServer'] = _MODELSERVER

# @@protoc_insertion_point(module_scope)
