
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-10-05T17:44:07+1100",
 "dirty": false,
 "error": null,
 "full-revisionid": "5d9d1b2ca7d01ffa1cde89a67b223ec0f0205596",
 "version": "v1.4.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
