# coding: utf-8

"""
    AVM

    This is api for AVM (automated valuation machine)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.addresses_api import AddressesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestAddressesApi(unittest.TestCase):
    """AddressesApi unit test stubs"""

    def setUp(self):
        self.api = AddressesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_address_properties(self):
        """Test case for get_address_properties

        """
        pass

    def test_get_similar_addresses(self):
        """Test case for get_similar_addresses

        """
        pass


if __name__ == '__main__':
    unittest.main()
