# coding: utf-8

"""
    AVM

    This is api for AVM (automated valuation machine)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.properties_api import PropertiesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestPropertiesApi(unittest.TestCase):
    """PropertiesApi unit test stubs"""

    def setUp(self):
        self.api = PropertiesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_properties_features(self):
        """Test case for get_properties_features

        """
        pass


if __name__ == '__main__':
    unittest.main()
