# coding: utf-8

"""
    AVM

    This is api for AVM (automated valuation machine)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.valuation_api import ValuationApi  # noqa: E501
from swagger_client.rest import ApiException


class TestValuationApi(unittest.TestCase):
    """ValuationApi unit test stubs"""

    def setUp(self):
        self.api = ValuationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_fast_valuation(self):
        """Test case for get_fast_valuation

        """
        pass

    def test_get_valuation(self):
        """Test case for get_valuation

        """
        pass


if __name__ == '__main__':
    unittest.main()
