#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

install_requires = \
['beautifulsoup4>=4.9.2', 'requests>=2.24.0']

extras_require = \
{'pdf': ['svglib>=1.0.1', 'reportlab>=3.5.53']}

entry_points = \
{'console_scripts': ['musdl = musdl:main']}

setup(name='musdl',
      version='2.2.1',
      description='[mus]escore [d]own[l]oader, ported from TypeScript',
      author='Ong Yong Xin',
      author_email='ongyongxin2020+github@gmail.com',
      url='https://github.com/ongyx/musdl',
      py_modules=['musdl'],
      install_requires=install_requires,
      extras_require=extras_require,
      entry_points=entry_points,
      python_requires='>=3.6',
     )
