
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-09-30T20:21:27-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "3d0bf02fe615b634b471f8571dcd1a1443d0eb03",
 "version": "3.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
