
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-10-06T06:36:27-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "dcf834475019209a0f008e23decf79f5328a89ed",
 "version": "v0.7.14a2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
