
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-10-08T20:29:27+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "b3e1d2dd7ac10d62cfb48640dbcf2d628e31d2ff",
 "version": "0.4.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
