# Generated by Django 2.2.4 on 2019-08-27 18:00

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('wagtailpress', '0003_auto_20190827_1725'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogarticlepage',
            options={'verbose_name': 'Blog article', 'verbose_name_plural': 'Blog articles'},
        ),
        migrations.CreateModel(
            name='BlogArticleAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='wagtailpress.BlogArticlePage')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_authors', to='wagtailcore.Page', verbose_name='Person page')),
            ],
            options={
                'verbose_name': 'Blog article author',
                'verbose_name_plural': 'Blog article authors',
            },
        ),
    ]
