# Generated by Django 2.2.4 on 2019-10-01 13:17

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('wagtailpress', '0007_auto_20190905_1332'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogArticlePageTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='blogarticlepage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='wagtailpress.BlogArticlePageTag', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.DeleteModel(
            name='BlogArtibclePageTag',
        ),
        migrations.AddField(
            model_name='blogarticlepagetag',
            name='content_object',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='wagtailpress.BlogArticlePage'),
        ),
        migrations.AddField(
            model_name='blogarticlepagetag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wagtailpress_blogarticlepagetag_items', to='taggit.Tag'),
        ),
    ]
