# Generated by Django 3.0.4 on 2020-04-23 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rest_sessions", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="verifytoken",
            options={
                "ordering": ["-created"],
                "verbose_name": "Verify Token",
                "verbose_name_plural": "Verify Tokens",
            },
        ),
    ]
