# Generated by Django 3.0.4 on 2020-08-13 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_sessions', '0002_auto_20200423_0913'),
    ]

    operations = [
        migrations.CreateModel(
            name='APISessionAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesses', to='rest_sessions.APISession')),
            ],
            options={
                'verbose_name': 'API session access',
                'verbose_name_plural': 'API session accesses',
            },
        ),
    ]
