# Generated by Django 2.2.13 on 2020-08-20 08:24

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_sessions', '0003_apisessionusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='apisession',
            name='token_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
    ]
