# Generated by Django 2.2.13 on 2020-08-20 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_sessions', '0004_apisession_token_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='apisession',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
