
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-10-04T16:17:08+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "728eb4513ebad64da110ca1d8627661904542f58",
 "version": "0.0.31"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
