
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-10-06T10:48:05+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "ea174677c09cd1fdeb44a2c8699ea95c1f90efff",
 "version": "0.13"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
