
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-09-30T09:09:58+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "8e52ab8e8d6147319c610aa515e21596df8a269f",
 "version": "1.13"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
