# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.1
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.


from . import _SimpleITKFiltersPython



from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError("Python 2.7 or later required")

# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _itkObjectnessImageFilterPython
else:
    import _itkObjectnessImageFilterPython

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

_swig_new_instance_method = _itkObjectnessImageFilterPython.SWIG_PyInstanceMethod_New
_swig_new_static_method = _itkObjectnessImageFilterPython.SWIG_PyStaticMethod_New

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


import itk.itkImageToImageFilterAPython
import itk.itkImageToImageFilterCommonPython
import itk.pyBasePython
import itk.itkVectorImagePython
import itk.ITKCommonBasePython
import itk.itkImagePython
import itk.itkRGBAPixelPython
import itk.itkFixedArrayPython
import itk.itkImageRegionPython
import itk.itkSizePython
import itk.itkIndexPython
import itk.itkOffsetPython
import itk.itkVectorPython
import itk.vnl_vector_refPython
import itk.vnl_vectorPython
import itk.stdcomplexPython
import itk.vnl_matrixPython
import itk.itkCovariantVectorPython
import itk.itkRGBPixelPython
import itk.itkSymmetricSecondRankTensorPython
import itk.itkMatrixPython
import itk.itkPointPython
import itk.vnl_matrix_fixedPython
import itk.itkVariableLengthVectorPython
import itk.itkImageSourcePython
import itk.itkImageSourceCommonPython

def itkObjectnessMeasureImageFilterID2ID2_New():
    return itkObjectnessMeasureImageFilterID2ID2.New()

class itkObjectnessMeasureImageFilterID2ID2(itk.itkImageToImageFilterAPython.itkImageToImageFilterID2ID2):
    r"""Proxy of C++ itkObjectnessMeasureImageFilterID2ID2 class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __New_orig__ = _swig_new_static_method(_itkObjectnessImageFilterPython.itkObjectnessMeasureImageFilterID2ID2___New_orig__)
    Clone = _swig_new_instance_method(_itkObjectnessImageFilterPython.itkObjectnessMeasureImageFilterID2ID2_Clone)
    SetAlpha = _swig_new_instance_method(_itkObjectnessImageFilterPython.itkObjectnessMeasureImageFilterID2ID2_SetAlpha)
    GetAlpha = _swig_new_instance_method(_itkObjectnessImageFilterPython.itkObjectnessMeasureImageFilterID2ID2_GetAlpha)
    SetBeta = _swig_new_instance_method(_itkObjectnessImageFilterPython.itkObjectnessMeasureImageFilterID2ID2_SetBeta)
    GetBeta = _swig_new_instance_method(_itkObjectnessImageFilterPython.itkObjectnessMeasureImageFilterID2ID2_GetBeta)
    SetGamma = _swig_new_instance_method(_itkObjectnessImageFilterPython.itkObjectnessMeasureImageFilterID2ID2_SetGamma)
    GetGamma = _swig_new_instance_method(_itkObjectnessImageFilterPython.itkObjectnessMeasureImageFilterID2ID2_GetGamma)
    SetScaleObjectnessMeasure = _swig_new_instance_method(_itkObjectnessImageFilterPython.itkObjectnessMeasureImageFilterID2ID2_SetScaleObjectnessMeasure)
    GetScaleObjectnessMeasure = _swig_new_instance_method(_itkObjectnessImageFilterPython.itkObjectnessMeasureImageFilterID2ID2_GetScaleObjectnessMeasure)
    ScaleObjectnessMeasureOn = _swig_new_instance_method(_itkObjectnessImageFilterPython.itkObjectnessMeasureImageFilterID2ID2_ScaleObjectnessMeasureOn)
    ScaleObjectnessMeasureOff = _swig_new_instance_method(_itkObjectnessImageFilterPython.itkObjectnessMeasureImageFilterID2ID2_ScaleObjectnessMeasureOff)
    SetObjectDimension = _swig_new_instance_method(_itkObjectnessImageFilterPython.itkObjectnessMeasureImageFilterID2ID2_SetObjectDimension)
    GetObjectDimension = _swig_new_instance_method(_itkObjectnessImageFilterPython.itkObjectnessMeasureImageFilterID2ID2_GetObjectDimension)
    SetBrightObject = _swig_new_instance_method(_itkObjectnessImageFilterPython.itkObjectnessMeasureImageFilterID2ID2_SetBrightObject)
    GetBrightObject = _swig_new_instance_method(_itkObjectnessImageFilterPython.itkObjectnessMeasureImageFilterID2ID2_GetBrightObject)
    BrightObjectOn = _swig_new_instance_method(_itkObjectnessImageFilterPython.itkObjectnessMeasureImageFilterID2ID2_BrightObjectOn)
    BrightObjectOff = _swig_new_instance_method(_itkObjectnessImageFilterPython.itkObjectnessMeasureImageFilterID2ID2_BrightObjectOff)
    __swig_destroy__ = _itkObjectnessImageFilterPython.delete_itkObjectnessMeasureImageFilterID2ID2
    cast = _swig_new_static_method(_itkObjectnessImageFilterPython.itkObjectnessMeasureImageFilterID2ID2_cast)

    def New(*args, **kargs):
        """New() -> itkObjectnessMeasureImageFilterID2ID2

        Create a new object of the class itkObjectnessMeasureImageFilterID2ID2 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          itkObjectnessMeasureImageFilterID2ID2.New(reader, threshold=10)

        is (most of the time) equivalent to:

          obj = itkObjectnessMeasureImageFilterID2ID2.New()
          obj.SetInput(0, reader.GetOutput())
          obj.SetThreshold(10)
        """
        obj = itkObjectnessMeasureImageFilterID2ID2.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)


# Register itkObjectnessMeasureImageFilterID2ID2 in _itkObjectnessImageFilterPython:
_itkObjectnessImageFilterPython.itkObjectnessMeasureImageFilterID2ID2_swigregister(itkObjectnessMeasureImageFilterID2ID2)
itkObjectnessMeasureImageFilterID2ID2___New_orig__ = _itkObjectnessImageFilterPython.itkObjectnessMeasureImageFilterID2ID2___New_orig__
itkObjectnessMeasureImageFilterID2ID2_cast = _itkObjectnessImageFilterPython.itkObjectnessMeasureImageFilterID2ID2_cast


def itkObjectnessMeasureImageFilterID3ID3_New():
    return itkObjectnessMeasureImageFilterID3ID3.New()

class itkObjectnessMeasureImageFilterID3ID3(itk.itkImageToImageFilterAPython.itkImageToImageFilterID3ID3):
    r"""Proxy of C++ itkObjectnessMeasureImageFilterID3ID3 class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __New_orig__ = _swig_new_static_method(_itkObjectnessImageFilterPython.itkObjectnessMeasureImageFilterID3ID3___New_orig__)
    Clone = _swig_new_instance_method(_itkObjectnessImageFilterPython.itkObjectnessMeasureImageFilterID3ID3_Clone)
    SetAlpha = _swig_new_instance_method(_itkObjectnessImageFilterPython.itkObjectnessMeasureImageFilterID3ID3_SetAlpha)
    GetAlpha = _swig_new_instance_method(_itkObjectnessImageFilterPython.itkObjectnessMeasureImageFilterID3ID3_GetAlpha)
    SetBeta = _swig_new_instance_method(_itkObjectnessImageFilterPython.itkObjectnessMeasureImageFilterID3ID3_SetBeta)
    GetBeta = _swig_new_instance_method(_itkObjectnessImageFilterPython.itkObjectnessMeasureImageFilterID3ID3_GetBeta)
    SetGamma = _swig_new_instance_method(_itkObjectnessImageFilterPython.itkObjectnessMeasureImageFilterID3ID3_SetGamma)
    GetGamma = _swig_new_instance_method(_itkObjectnessImageFilterPython.itkObjectnessMeasureImageFilterID3ID3_GetGamma)
    SetScaleObjectnessMeasure = _swig_new_instance_method(_itkObjectnessImageFilterPython.itkObjectnessMeasureImageFilterID3ID3_SetScaleObjectnessMeasure)
    GetScaleObjectnessMeasure = _swig_new_instance_method(_itkObjectnessImageFilterPython.itkObjectnessMeasureImageFilterID3ID3_GetScaleObjectnessMeasure)
    ScaleObjectnessMeasureOn = _swig_new_instance_method(_itkObjectnessImageFilterPython.itkObjectnessMeasureImageFilterID3ID3_ScaleObjectnessMeasureOn)
    ScaleObjectnessMeasureOff = _swig_new_instance_method(_itkObjectnessImageFilterPython.itkObjectnessMeasureImageFilterID3ID3_ScaleObjectnessMeasureOff)
    SetObjectDimension = _swig_new_instance_method(_itkObjectnessImageFilterPython.itkObjectnessMeasureImageFilterID3ID3_SetObjectDimension)
    GetObjectDimension = _swig_new_instance_method(_itkObjectnessImageFilterPython.itkObjectnessMeasureImageFilterID3ID3_GetObjectDimension)
    SetBrightObject = _swig_new_instance_method(_itkObjectnessImageFilterPython.itkObjectnessMeasureImageFilterID3ID3_SetBrightObject)
    GetBrightObject = _swig_new_instance_method(_itkObjectnessImageFilterPython.itkObjectnessMeasureImageFilterID3ID3_GetBrightObject)
    BrightObjectOn = _swig_new_instance_method(_itkObjectnessImageFilterPython.itkObjectnessMeasureImageFilterID3ID3_BrightObjectOn)
    BrightObjectOff = _swig_new_instance_method(_itkObjectnessImageFilterPython.itkObjectnessMeasureImageFilterID3ID3_BrightObjectOff)
    __swig_destroy__ = _itkObjectnessImageFilterPython.delete_itkObjectnessMeasureImageFilterID3ID3
    cast = _swig_new_static_method(_itkObjectnessImageFilterPython.itkObjectnessMeasureImageFilterID3ID3_cast)

    def New(*args, **kargs):
        """New() -> itkObjectnessMeasureImageFilterID3ID3

        Create a new object of the class itkObjectnessMeasureImageFilterID3ID3 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          itkObjectnessMeasureImageFilterID3ID3.New(reader, threshold=10)

        is (most of the time) equivalent to:

          obj = itkObjectnessMeasureImageFilterID3ID3.New()
          obj.SetInput(0, reader.GetOutput())
          obj.SetThreshold(10)
        """
        obj = itkObjectnessMeasureImageFilterID3ID3.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)


# Register itkObjectnessMeasureImageFilterID3ID3 in _itkObjectnessImageFilterPython:
_itkObjectnessImageFilterPython.itkObjectnessMeasureImageFilterID3ID3_swigregister(itkObjectnessMeasureImageFilterID3ID3)
itkObjectnessMeasureImageFilterID3ID3___New_orig__ = _itkObjectnessImageFilterPython.itkObjectnessMeasureImageFilterID3ID3___New_orig__
itkObjectnessMeasureImageFilterID3ID3_cast = _itkObjectnessImageFilterPython.itkObjectnessMeasureImageFilterID3ID3_cast


def itkObjectnessMeasureImageFilterIF2IF2_New():
    return itkObjectnessMeasureImageFilterIF2IF2.New()

class itkObjectnessMeasureImageFilterIF2IF2(itk.itkImageToImageFilterAPython.itkImageToImageFilterIF2IF2):
    r"""Proxy of C++ itkObjectnessMeasureImageFilterIF2IF2 class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __New_orig__ = _swig_new_static_method(_itkObjectnessImageFilterPython.itkObjectnessMeasureImageFilterIF2IF2___New_orig__)
    Clone = _swig_new_instance_method(_itkObjectnessImageFilterPython.itkObjectnessMeasureImageFilterIF2IF2_Clone)
    SetAlpha = _swig_new_instance_method(_itkObjectnessImageFilterPython.itkObjectnessMeasureImageFilterIF2IF2_SetAlpha)
    GetAlpha = _swig_new_instance_method(_itkObjectnessImageFilterPython.itkObjectnessMeasureImageFilterIF2IF2_GetAlpha)
    SetBeta = _swig_new_instance_method(_itkObjectnessImageFilterPython.itkObjectnessMeasureImageFilterIF2IF2_SetBeta)
    GetBeta = _swig_new_instance_method(_itkObjectnessImageFilterPython.itkObjectnessMeasureImageFilterIF2IF2_GetBeta)
    SetGamma = _swig_new_instance_method(_itkObjectnessImageFilterPython.itkObjectnessMeasureImageFilterIF2IF2_SetGamma)
    GetGamma = _swig_new_instance_method(_itkObjectnessImageFilterPython.itkObjectnessMeasureImageFilterIF2IF2_GetGamma)
    SetScaleObjectnessMeasure = _swig_new_instance_method(_itkObjectnessImageFilterPython.itkObjectnessMeasureImageFilterIF2IF2_SetScaleObjectnessMeasure)
    GetScaleObjectnessMeasure = _swig_new_instance_method(_itkObjectnessImageFilterPython.itkObjectnessMeasureImageFilterIF2IF2_GetScaleObjectnessMeasure)
    ScaleObjectnessMeasureOn = _swig_new_instance_method(_itkObjectnessImageFilterPython.itkObjectnessMeasureImageFilterIF2IF2_ScaleObjectnessMeasureOn)
    ScaleObjectnessMeasureOff = _swig_new_instance_method(_itkObjectnessImageFilterPython.itkObjectnessMeasureImageFilterIF2IF2_ScaleObjectnessMeasureOff)
    SetObjectDimension = _swig_new_instance_method(_itkObjectnessImageFilterPython.itkObjectnessMeasureImageFilterIF2IF2_SetObjectDimension)
    GetObjectDimension = _swig_new_instance_method(_itkObjectnessImageFilterPython.itkObjectnessMeasureImageFilterIF2IF2_GetObjectDimension)
    SetBrightObject = _swig_new_instance_method(_itkObjectnessImageFilterPython.itkObjectnessMeasureImageFilterIF2IF2_SetBrightObject)
    GetBrightObject = _swig_new_instance_method(_itkObjectnessImageFilterPython.itkObjectnessMeasureImageFilterIF2IF2_GetBrightObject)
    BrightObjectOn = _swig_new_instance_method(_itkObjectnessImageFilterPython.itkObjectnessMeasureImageFilterIF2IF2_BrightObjectOn)
    BrightObjectOff = _swig_new_instance_method(_itkObjectnessImageFilterPython.itkObjectnessMeasureImageFilterIF2IF2_BrightObjectOff)
    __swig_destroy__ = _itkObjectnessImageFilterPython.delete_itkObjectnessMeasureImageFilterIF2IF2
    cast = _swig_new_static_method(_itkObjectnessImageFilterPython.itkObjectnessMeasureImageFilterIF2IF2_cast)

    def New(*args, **kargs):
        """New() -> itkObjectnessMeasureImageFilterIF2IF2

        Create a new object of the class itkObjectnessMeasureImageFilterIF2IF2 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          itkObjectnessMeasureImageFilterIF2IF2.New(reader, threshold=10)

        is (most of the time) equivalent to:

          obj = itkObjectnessMeasureImageFilterIF2IF2.New()
          obj.SetInput(0, reader.GetOutput())
          obj.SetThreshold(10)
        """
        obj = itkObjectnessMeasureImageFilterIF2IF2.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)


# Register itkObjectnessMeasureImageFilterIF2IF2 in _itkObjectnessImageFilterPython:
_itkObjectnessImageFilterPython.itkObjectnessMeasureImageFilterIF2IF2_swigregister(itkObjectnessMeasureImageFilterIF2IF2)
itkObjectnessMeasureImageFilterIF2IF2___New_orig__ = _itkObjectnessImageFilterPython.itkObjectnessMeasureImageFilterIF2IF2___New_orig__
itkObjectnessMeasureImageFilterIF2IF2_cast = _itkObjectnessImageFilterPython.itkObjectnessMeasureImageFilterIF2IF2_cast


def itkObjectnessMeasureImageFilterIF3IF3_New():
    return itkObjectnessMeasureImageFilterIF3IF3.New()

class itkObjectnessMeasureImageFilterIF3IF3(itk.itkImageToImageFilterAPython.itkImageToImageFilterIF3IF3):
    r"""Proxy of C++ itkObjectnessMeasureImageFilterIF3IF3 class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __New_orig__ = _swig_new_static_method(_itkObjectnessImageFilterPython.itkObjectnessMeasureImageFilterIF3IF3___New_orig__)
    Clone = _swig_new_instance_method(_itkObjectnessImageFilterPython.itkObjectnessMeasureImageFilterIF3IF3_Clone)
    SetAlpha = _swig_new_instance_method(_itkObjectnessImageFilterPython.itkObjectnessMeasureImageFilterIF3IF3_SetAlpha)
    GetAlpha = _swig_new_instance_method(_itkObjectnessImageFilterPython.itkObjectnessMeasureImageFilterIF3IF3_GetAlpha)
    SetBeta = _swig_new_instance_method(_itkObjectnessImageFilterPython.itkObjectnessMeasureImageFilterIF3IF3_SetBeta)
    GetBeta = _swig_new_instance_method(_itkObjectnessImageFilterPython.itkObjectnessMeasureImageFilterIF3IF3_GetBeta)
    SetGamma = _swig_new_instance_method(_itkObjectnessImageFilterPython.itkObjectnessMeasureImageFilterIF3IF3_SetGamma)
    GetGamma = _swig_new_instance_method(_itkObjectnessImageFilterPython.itkObjectnessMeasureImageFilterIF3IF3_GetGamma)
    SetScaleObjectnessMeasure = _swig_new_instance_method(_itkObjectnessImageFilterPython.itkObjectnessMeasureImageFilterIF3IF3_SetScaleObjectnessMeasure)
    GetScaleObjectnessMeasure = _swig_new_instance_method(_itkObjectnessImageFilterPython.itkObjectnessMeasureImageFilterIF3IF3_GetScaleObjectnessMeasure)
    ScaleObjectnessMeasureOn = _swig_new_instance_method(_itkObjectnessImageFilterPython.itkObjectnessMeasureImageFilterIF3IF3_ScaleObjectnessMeasureOn)
    ScaleObjectnessMeasureOff = _swig_new_instance_method(_itkObjectnessImageFilterPython.itkObjectnessMeasureImageFilterIF3IF3_ScaleObjectnessMeasureOff)
    SetObjectDimension = _swig_new_instance_method(_itkObjectnessImageFilterPython.itkObjectnessMeasureImageFilterIF3IF3_SetObjectDimension)
    GetObjectDimension = _swig_new_instance_method(_itkObjectnessImageFilterPython.itkObjectnessMeasureImageFilterIF3IF3_GetObjectDimension)
    SetBrightObject = _swig_new_instance_method(_itkObjectnessImageFilterPython.itkObjectnessMeasureImageFilterIF3IF3_SetBrightObject)
    GetBrightObject = _swig_new_instance_method(_itkObjectnessImageFilterPython.itkObjectnessMeasureImageFilterIF3IF3_GetBrightObject)
    BrightObjectOn = _swig_new_instance_method(_itkObjectnessImageFilterPython.itkObjectnessMeasureImageFilterIF3IF3_BrightObjectOn)
    BrightObjectOff = _swig_new_instance_method(_itkObjectnessImageFilterPython.itkObjectnessMeasureImageFilterIF3IF3_BrightObjectOff)
    __swig_destroy__ = _itkObjectnessImageFilterPython.delete_itkObjectnessMeasureImageFilterIF3IF3
    cast = _swig_new_static_method(_itkObjectnessImageFilterPython.itkObjectnessMeasureImageFilterIF3IF3_cast)

    def New(*args, **kargs):
        """New() -> itkObjectnessMeasureImageFilterIF3IF3

        Create a new object of the class itkObjectnessMeasureImageFilterIF3IF3 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          itkObjectnessMeasureImageFilterIF3IF3.New(reader, threshold=10)

        is (most of the time) equivalent to:

          obj = itkObjectnessMeasureImageFilterIF3IF3.New()
          obj.SetInput(0, reader.GetOutput())
          obj.SetThreshold(10)
        """
        obj = itkObjectnessMeasureImageFilterIF3IF3.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)


# Register itkObjectnessMeasureImageFilterIF3IF3 in _itkObjectnessImageFilterPython:
_itkObjectnessImageFilterPython.itkObjectnessMeasureImageFilterIF3IF3_swigregister(itkObjectnessMeasureImageFilterIF3IF3)
itkObjectnessMeasureImageFilterIF3IF3___New_orig__ = _itkObjectnessImageFilterPython.itkObjectnessMeasureImageFilterIF3IF3___New_orig__
itkObjectnessMeasureImageFilterIF3IF3_cast = _itkObjectnessImageFilterPython.itkObjectnessMeasureImageFilterIF3IF3_cast


import itkHelpers
@itkHelpers.accept_numpy_array_like_xarray
def objectness_measure_image_filter(*args, **kwargs):
    """Procedural interface for ObjectnessMeasureImageFilter"""
    import itk
    instance = itk.ObjectnessMeasureImageFilter.New(*args, **kwargs)
    return instance.__internal_call__()

def objectness_measure_image_filter_init_docstring():
    import itk
    import itkTemplate
    import itkHelpers
    if isinstance(itk.ObjectnessMeasureImageFilter, itkTemplate.itkTemplate):
        filter_object = itk.ObjectnessMeasureImageFilter.values()[0]
    else:
        filter_object = itk.ObjectnessMeasureImageFilter

    objectness_measure_image_filter.__doc__ = filter_object.__doc__
    objectness_measure_image_filter.__doc__ += "\n Args are Input(s) to the filter.\n"
    objectness_measure_image_filter.__doc__ += "\n Available Keyword Arguments:\n"
    if isinstance(itk.ObjectnessMeasureImageFilter, itkTemplate.itkTemplate):
        objectness_measure_image_filter.__doc__ += itkHelpers.filter_args(filter_object)[0]
        objectness_measure_image_filter.__doc__ += "\n"
        objectness_measure_image_filter.__doc__ += itkHelpers.filter_args(filter_object)[1]
    else:
        objectness_measure_image_filter.__doc__ += "".join([
            "  " + itkHelpers.camel_to_snake_case(item[3:]) + "\n"
            for item in dir(filter_object)
            if item.startswith("Set")])



