
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-10-08T14:54:33-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "5667153875d95453b80c1472f265a3e9a128583a",
 "version": "1.5.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
