variable resource_group_name {}
variable location {}
variable user {}
variable password {}
variable size {}
variable upload_folder {}
variable subnet_cidr {}
variable vnet_name {}
variable ssh_private_key {}
variable ssh_pub_key {}
variable kube_config {}
