
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-10-09T14:56:56-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "497dfdd7f15eec2c67bc03fcfdb1b47f0593b3e8",
 "version": "0.0.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
