# coding: utf-8

"""
    ENBISYS AVM API

    API for ENBISYS AVM-platform  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: avm@enbisys.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import enbisysavm
from enbisysavm.models.response_required_features import ResponseRequiredFeatures  # noqa: E501
from enbisysavm.rest import ApiException


class TestResponseRequiredFeatures(unittest.TestCase):
    """ResponseRequiredFeatures unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testResponseRequiredFeatures(self):
        """Test ResponseRequiredFeatures"""
        # FIXME: construct object with mandatory attributes with example values
        # model = enbisysavm.models.response_required_features.ResponseRequiredFeatures()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
