
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-10-05T13:55:32+1100",
 "dirty": false,
 "error": null,
 "full-revisionid": "864edb713e46eff9df08fc3233103a4b8d6a3aab",
 "version": "2.0.0rc7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
