from . import test_subscription_request
from . import test_coop_agreement
from . import test_contract
from . import test_service_supplier
from . import test_product_category_technology_supplier
from . import test_crm_lead_line
from . import test_mobile_isp_info
from . import test_broadband_isp_info
from . import test_res_partner
from . import test_crm_lead_service
from . import test_contract_contract_service
from . import test_previous_provider_service
from . import test_production_lot
from . import test_stock_move_line
from . import test_adsl_data_from_crm_lead_line
from . import test_fiber_data_from_crm_lead_line
from . import test_mobile_data_from_crm_lead_line
