
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-10-08T16:50:21+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "322398f59e2114b6d991f160de1341e08d51fed4",
 "version": "1.13.0.post.dev148"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
