
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-10-04T21:20:24-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "42ab37b59853a2cc714e8228eac0915f9d77794c",
 "version": "0.9.42"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
