
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-10-06T00:54:46+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "669d242a02dbbbdc2066ff5e6c49ab39a0d0f9e0",
 "version": "0.0.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
