#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['daves_utilities']

package_data = \
{'': ['*'],
 'daves_utilities': ['data/*',
                     'data/.fun_save/*',
                     'test/*',
                     'test/.pytest_cache/*',
                     'test/.pytest_cache/v/*',
                     'test/.pytest_cache/v/cache/*']}

setup(name='daves_utilities',
      version='0.0.13',
      description='Daves utilities is a collection of useful python functions which I would like to provide to anybody who is interested in using them.',
      author='David Kuchelmeister',
      author_email='kuchelmeister.david@gmail.com',
      url='https://github.com/kuchedav/daves_utilities',
      packages=packages,
      package_data=package_data,
     )
