
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-10-09T07:57:21+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "06b5e54cfdc7a2df5637d44da828dc25c4d2a158",
 "version": "0.3.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
