
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-10-09T16:26:19+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "bc1cfdb60dead8c46654b922034c24307bcfb1f6",
 "version": "v0.9.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
