
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-10-04T15:07:47-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "8c3baeb7d4337b7eec0330414bcc2951c72afefa",
 "version": "0.0.15"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
