
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-10-02T15:12:06-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "0b52e9b31e09eca794c058b635267c182f864b9a",
 "version": "1.10.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
