
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-10-02T19:30:37+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "3a13d9fd465c5cdc441c369e86c12fee30eddf38",
 "version": "v0.6.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
