
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-10-01T16:35:04-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "b68cc1c6d4d5dd1a3e9e35e1267aedfcca7f1e47",
 "version": "0.50a0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
