
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-10-03T15:37:53.273384",
 "dirty": false,
 "error": null,
 "full-revisionid": "eaa65872b8c98b30b5cb72620259ccc6043d1505",
 "version": "0.7.0.post1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
