#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['fastapi_permissions']

package_data = \
{'': ['*']}

install_requires = \
['fastapi >= 0.33.0', 'python-multipart >= 0.0.5']

extras_require = \
{'dev': ['black',
         'flake8',
         'flake8-comprehensions',
         'isort >= 5.0.0',
         'keyring',
         'pre-commit',
         'pyjwt',
         'passlib[bcrypt]',
         'fastapi[all]'],
 'test': ['pytest >= 4.0.0',
          'pytest-cov',
          'pytest-mock',
          'pytest-asyncio',
          'pytest-randomly',
          'tox']}

setup(name='fastapi_permissions',
      version='0.2.7',
      description='Row Level Permissions for FastAPI',
      author='Holger Frey',
      author_email='mail@holgerfrey.de',
      url='https://github.com/holgi/fastapi-permissions',
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      extras_require=extras_require,
      python_requires='>=3.6',
     )
