
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-10-06T18:12:52+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "a9b55776fc93dcca40f0fb42c9a99ea5b841e910",
 "version": "0.3.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
