# Generated by Django 2.2.4 on 2019-08-21 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailperson', '0002_auto_20190820_1942'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personindexpage',
            options={'verbose_name': 'Person Index Page', 'verbose_name_plural': 'Person Index Pages'},
        ),
    ]
