# Generated by Django 2.2.4 on 2019-08-21 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailperson', '0003_auto_20190821_1817'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PersonPageTitle',
            new_name='PersonTitlePage',
        ),
        migrations.AlterModelOptions(
            name='persontitlepage',
            options={'verbose_name': 'Person Title Page', 'verbose_name_plural': 'Person Title Pages'},
        ),
    ]
