# Generated by Django 3.0.5 on 2020-04-16 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailperson', '0005_auto_20200220_1854'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personpage',
            options={'ordering': ['title'], 'verbose_name': 'Person or author page', 'verbose_name_plural': 'Person or author pages'},
        ),
        migrations.AddField(
            model_name='person',
            name='name_slug',
            field=models.CharField(blank=True, editable=False, max_length=250),
        ),
    ]
