
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-10-08T12:19:49+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "1c818465f0201af12814ba5a41a7a5294c046500",
 "version": "0.6.0.post.dev16"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
