name='mglcmdtools'

from .mglcmdtools import rm_and_mkdir, runcmd, longStrings_not_match_shortStrings,read_fastaLike,read_fastaLike2,csv2dict,csv2tupe, split_fasta_to_equal_size, extend_ambiguous_dna, extend_ambiguous_dna_randomly