
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-10-02T18:22:26-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "a80b867cf40b05aa423a19aea1a077764ffba0f4",
 "version": "2.29.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
