
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-09-29T15:05:55-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "d0c07bbf14296c6965c7827df90de675d5e01bc7",
 "version": "1.10.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
