
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-10-08T19:30:38-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "c1fc05c37653765aa9e0da140ddce9372d2aef94",
 "version": "0.4.8.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
