
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-09-17T09:29:18-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "ea4682d3dda3504031fd5e56061da31f78fbd53b",
 "version": "1.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
