
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "8a699223982ce8425f59f048d0163090b4a81193",
 "version": "2.29.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
