
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-10-01T10:42:47+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "a5cc9022bbe864de28d79f2f8048d69c9be3b46f",
 "version": "0.3.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
