
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-10-07T16:40:41-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "7beef40e426a203883f63c144d546b79f30ed355",
 "version": "2020.10.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
