# coding: utf-8

"""
    ENBISYS AVM API

    API for ENBISYS AVM-platform  # noqa: E501

    OpenAPI spec version: 1.0.1
    Contact: avm@enbisys.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class ModelProperty(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'property_id': 'int',
        'flat': 'str'
    }

    attribute_map = {
        'property_id': 'propertyId',
        'flat': 'flat'
    }

    def __init__(self, property_id=None, flat=None):  # noqa: E501
        """ModelProperty - a model defined in OpenAPI"""  # noqa: E501

        self._property_id = None
        self._flat = None
        self.discriminator = None

        if property_id is not None:
            self.property_id = property_id
        if flat is not None:
            self.flat = flat

    @property
    def property_id(self):
        """Gets the property_id of this ModelProperty.  # noqa: E501

        Property id  # noqa: E501

        :return: The property_id of this ModelProperty.  # noqa: E501
        :rtype: int
        """
        return self._property_id

    @property_id.setter
    def property_id(self, property_id):
        """Sets the property_id of this ModelProperty.

        Property id  # noqa: E501

        :param property_id: The property_id of this ModelProperty.  # noqa: E501
        :type: int
        """

        self._property_id = property_id

    @property
    def flat(self):
        """Gets the flat of this ModelProperty.  # noqa: E501

        Flat  # noqa: E501

        :return: The flat of this ModelProperty.  # noqa: E501
        :rtype: str
        """
        return self._flat

    @flat.setter
    def flat(self, flat):
        """Sets the flat of this ModelProperty.

        Flat  # noqa: E501

        :param flat: The flat of this ModelProperty.  # noqa: E501
        :type: str
        """

        self._flat = flat

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ModelProperty):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
