
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-10-01T11:50:41-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "e0fce95ba4dea4b7b6d6f0c6bf744286cf86a5e0",
 "version": "v0.14.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
