# Generated by Django 2.2.12 on 2020-05-13 15:17

from django.db import migrations, models
import django.db.models.deletion
import djangocms_socialshare.models
import enumfields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialSharePluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='djangocms_socialshare_socialsharepluginmodel', serialize=False, to='cms.CMSPlugin')),
                ('alignment', enumfields.fields.EnumField(default='left', enum=djangocms_socialshare.models.Alignment, max_length=32)),
                ('size', models.IntegerField(default=25, help_text='In pixels')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='SocialShareButton',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', enumfields.fields.EnumField(default='facebook', enum=djangocms_socialshare.models.Type, max_length=32)),
                ('order', models.PositiveIntegerField(default=0)),
                ('plugin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buttons', to='djangocms_socialshare.SocialSharePluginModel')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
