
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-10-08T10:26:03+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "41034dda2adffe8a716afe87e4ab3046784b7256",
 "version": "0.18.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
