
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-10-08T03:22:31+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "8ef7e4da3967cf713a8bb52e750f2dadbf4799d8",
 "version": "1.13.0.post.dev140"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
