
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-09-25T16:53:19+0900",
 "dirty": false,
 "error": null,
 "full-revisionid": "ece1192d5f5d6c737fe7e44b29da29980b9f4507",
 "version": "1.6.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
