
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-10-02T17:05:54-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "3a05aa8ecbca7bc4bf45890db8c0dde0f05f7449",
 "version": "v0.17.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
