
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-10-05T16:24:02-0600",
 "dirty": true,
 "error": null,
 "full-revisionid": "6466c1a34a524e29c4c26ee56a5a1f243bfcc1e5",
 "version": "0.0.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
