# Generated by Django 3.1.2 on 2020-10-04 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramAPISettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ig_username', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Instagram username')),
            ],
            options={
                'verbose_name': 'IG LINK',
                'verbose_name_plural': 'IG LINK SETTINGS',
            },
        ),
    ]
