
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-10-01T10:21:28+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "f7838334e34c067f4864d28bf82ece6d0e83a120",
 "version": "0.4.122"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
