
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-10-08T14:50:45-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "cb2457ba6f3777cda0451d63020fd4d0668975c7",
 "version": "0.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
