#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['vendoring', 'vendoring.tasks']

package_data = \
{'': ['*']}

package_dir = \
{'': 'src'}

install_requires = \
['click', 'jsonschema', 'toml', 'requests', 'packaging']

extras_require = \
{'doc': ['sphinx'],
 'test': ['pytest', 'pytest-xdist', 'pytest-cov', 'pytest-mock']}

entry_points = \
{'console_scripts': ['vendoring = vendoring.cli:main']}

setup(name='vendoring',
      version='0.3.3',
      description='A command line tool, to simplify vendoring pure Python dependencies.',
      author='Pradyun Gedam',
      author_email='pradyunsg@gmail.com',
      url='https://github.com/pradyunsg/vendoring',
      packages=packages,
      package_data=package_data,
      package_dir=package_dir,
      install_requires=install_requires,
      extras_require=extras_require,
      entry_points=entry_points,
      python_requires='~= 3.8',
     )
