# Generated by Django 2.2.15 on 2020-10-03 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0009_importsetupaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='importsetup',
            name='metadata_map',
        ),
    ]
