
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-09-30T10:36:29-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "bca4def081b2767a4eef09697844b1820a6cec56",
 "version": "2.4.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
